[build]
  publish = "public/"
  command = "hugo --gc --minify"
[context.production.environment]
  HUGO_VERSION = "0.59.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"
[context.split1]
  command = "hugo --gc --minify"
[context.split1.environment]
  HUGO_VERSION = "0.59.1"
  HUGO_ENV = "production"
[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.59.1"
[context.branch-deploy]
    acommand = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.59.1"
[context.next.environment]
  HUGO_ENABLEGITINFO = "false"
[[redirects]]
  from ="/vendor/bulma.css"
  to = "https://svelte-base64.netlify.com/vendor/bulma.css"
  status = 200
  force = true
[[redirects]]
  from ="/vendor/bulma.css.map"
  to = "https://svelte-base64.netlify.com/vendor/bulma.css.map"
  status = 200
  force = true
[[redirects]]
  from ="/vendor/all.css"
  to = "https://svelte-base64.netlify.com/vendor/all.css"
  status = 200
  force = true
[[redirects]]
  from ="/global.css"
  to = "https://svelte-base64.netlify.com/global.css"
  status = 200
  force = true
[[redirects]]
  from ="/favicon.png"
  to = "https://svelte-base64.netlify.com/favicon.png"
  status = 200
  force = true
[[redirects]]
  from ="/logo-192.png"
  to = "https://svelte-base64.netlify.com/logo-192.png"
  status = 200
  force = true
[[redirects]]
  from ="/logo-512.png"
  to = "https://svelte-base64.netlify.com/logo-512.png"
  status = 200
  force = true
[[redirects]]
  from ="/base64/*"
  to = "https://svelte-base64.netlify.com/base64/:splat"
  status = 200
  force = true
[[redirects]]
  from ="/client/*"
  to = "https://svelte-base64.netlify.com/client/:splat"
  status = 200
  force = true
