[build]
  publish = "public/"
  command = "hugo --gc --minify"
[context.production.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"
[context.split1]
  command = "hugo --gc --minify"
[context.split1.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"
[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.68.3"
[context.branch-deploy]
    acommand = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.68.3"
[context.next.environment]
  HUGO_ENABLEGITINFO = "false"
[[redirects]]
  from ="/build/bundle.js"
  to = "https://svelte-base64.netlify.com/build/bundle.js"
  status = 200
  force = true
[[redirects]]
  from ="/build/bundle.css"
  to = "https://svelte-base64.netlify.com/build/bundle.css"
  status = 200
  force = true
[[redirects]]
  from ="/build/global.css"
  to = "https://svelte-base64.netlify.com/build/global.css"
  status = 200
  force = true
[[redirects]]
  from ="/webfonts/*"
  to = "https://svelte-base64.netlify.com/webfonts/:splat"
  status = 200
  force = true
[[redirects]]
  from ="/favicon.png"
  to = "https://svelte-base64.netlify.com/favicon.png"
  status = 200
  force = true
[[redirects]]
  from ="/base64/*"
  to = "https://svelte-base64.netlify.com/:splat"
  status = 200
  force = true
